version: '2'

networks:
  nsit:
services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-arjun
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.arjun.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.arjun.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/arjun.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerarjun
    networks:
      - nsit

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-dharmesh
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.dharmesh.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.dharmesh.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/dharmesh.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerdharmesh
    networks:
      - nsit

  ca2:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-madhur
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.madhur.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.madhur.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/madhur.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peermadhur
    networks:
      - nsit

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - nsit

  peer0.arjun.example.com:
    container_name: peer0.arjun.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.arjun.example.com
    networks:
      - nsit

  peer1.arjun.example.com:
    container_name: peer1.arjun.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.arjun.example.com
    networks:
      - nsit

  peer0.dharmesh.example.com:
    container_name: peer0.dharmesh.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.dharmesh.example.com
    networks:
      - nsit

  peer1.dharmesh.example.com:
    container_name: peer1.dharmesh.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.dharmesh.example.com
    networks:
      - nsit

  peer0.madhur.example.com:
    container_name: peer0.madhur.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.madhur.example.com
    networks:
      - nsit

  peer1.madhur.example.com:
    container_name: peer1.madhur.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.madhur.example.com
    networks:
      - nsit
